version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    steps:
      - run:
          name: Install Node Modules
          command: npm install
      - run:
            name: Test
            command: npm run test
workflows:
  test:
    jobs:
      - test
