version: 2.1
jobs:
  run-tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          comand: |
          npm install --save
      - run:
          name: Run tests
          comand: |
          node ./node_modules/@wdio/cli/bin/wdio.js
workflows:
  build_test:
    jobs:
      - run_tests



