version: 2.1
jobs:
  run-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install npm dependencies
          command: npm install --save
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: node_modules/.bin/wdio wdio.conf.js
      - run:
          name: Generate Allure Report
          command: allure generate allure-results
      - store_test_results:
          path: ./allure-results
workflows:
  build_test:
    jobs:
      - run-tests
